---
title: "forecast_walmart"
author: "Moab Alves"
date: "2023-11-24"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(forecast)
library(tidyr)

```

## Leitura dos Dados

```{r leitura dos dados}
data <- read.csv("C:/Users/moaba/OneDrive/Documentos/forecast-r/walmart-sales-dataset-of-45stores.csv")

names(data)
head(data)
```

## Preparando os dados


```{r}
lojas <- data %>%
  select(Store, Weekly_Sales, Date) %>%
  rename(store = Store, weekly_sales = Weekly_Sales, date = Date) %>%
  group_by(store)
```

## Criando a série temporal

```{r}
ts_loja <- lojas %>%
  filter(store == 1) %>%
  ungroup() %>%
  select(weekly_sales) %>%
  ts(frequency = 52, start = c(2010,5), end = c(2012,43))

autoplot(ts_loja) +
  ggtitle("Walmart: vendas da loja 1") +
  xlab("Ano") +
  ylab("Vendas")
```

### Sazonalidade

```{r, fig.width=9, fig.height = 5}
ggseasonplot(ts_loja) +
  ggtitle("Sazonalidade das vendas") +
  xlab("Semana") + 
  ylab("Vendas")
```

## Forecast

```{r, fig.width=9, fig.height = 5}
autoplot(forecast(ts_loja))
```

### Usando o modelo de regressão linear

```{r, fig.width=9, fig.height = 5}
fit_loja1 <- tslm(ts_loja ~ season + trend)
fc_linear <- forecast(fit_loja1, h = 104)
autoplot(fc_linear)
```
